kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{.Release.Name}}-environment
data:
  {{- if .Values.indexer.rpcs.ethereum }}
  ETHEREUM_RPC: {{ .Values.indexer.rpcs.ethereum }}
  {{- end }}
  {{- if .Values.indexer.rpcs.moonbeam }}
  MOONBEAM_RPC: {{ .Values.indexer.rpcs.moonbeam }}
  {{- end }}
  {{- if .Values.indexer.rpcs.kovan }}
  KOVAN_RPC: {{ .Values.indexer.rpcs.kovan }}
  {{- end }}
  {{- if .Values.indexer.rpcs.rinkeby }}
  RINKEBY_RPC: {{ .Values.indexer.rpcs.rinkeby }}
  {{- end }}
  {{- if .Values.indexer.rpcs.moonbasealpha }}
  MOONBASEALPHA_RPC: {{ .Values.indexer.rpcs.moonbasealpha }}
  {{- end }}
  ENVIRONMENT: {{ .Values.indexer.environment }}

  PORT: {{ .Values.indexer.internalPort }}
  PROGRAM: "core"
  PGHOST: {{ .Values.indexer.postgres.host }}
  PGUSER: {{ .Values.indexer.postgres.user }}
  PGDATABASE: {{ .Values.indexer.postgres.database }}
  PGPASSWORD: {{ .Values.indexer.postgres.password }}
  PGPORT: {{ .Values.indexer.postgres.port }}

---

kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{.Release.Name}}-service-account
data:
  service_account.json: |
  {{ .Values.cloudsqlProxy.serviceAccountJson }}