apiVersion: v1 
kind: ConfigMap 
metadata:
  name: {{ .Release.Name }}-indexer-env
data:
  {{- if .Values.indexer.rpcs.ethereum }}
  ETHEREUM_RPC: {{ .Values.indexer.rpcs.ethereum | quote }}
  {{- end }}
  {{- if .Values.indexer.rpcs.moonbeam }}
  MOONBEAM_RPC: {{ .Values.indexer.rpcs.moonbeam | quote }}
  {{- end }}
  {{- if .Values.indexer.rpcs.kovan }}
  KOVAN_RPC: {{ .Values.indexer.rpcs.kovan | quote }}
  {{- end }}
  {{- if .Values.indexer.rpcs.rinkeby }}
  RINKEBY_RPC: {{ .Values.indexer.rpcs.rinkeby | quote }}
  {{- end }}
  {{- if .Values.indexer.rpcs.moonbasealpha | quote }}
  MOONBASEALPHA_RPC: {{ .Values.indexer.rpcs.moonbasealpha | quote }}
  {{- end }}
  {{- if .Values.indexer.rpcs.milkomedatestnet | quote }}
  MILKOMEDATESTNET_RPC: {{ .Values.indexer.rpcs.milkomedatestnet | quote }}
  {{- end }}
  ENVIRONMENT: {{ .Values.environment | quote }}

  PORT: {{ .Values.indexer.internalPort | quote }}
  BATCH_SIZE: {{ .Values.indexer.rpc_batch_size | quote }}
  PROGRAM: "core"
  DATABASE_URL: postgres://{{ .Values.indexer.db.user }}:{{ .Values.indexer.db.password }}@{{ tpl .Values.indexer.db.host . }}:{{ .Values.indexer.db.port }}/{{ .Values.indexer.db.database }}?connect_timeout=300&schema=public