    apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.environment }}-indexer
  labels:
    environment: {{ .Values.environment }}
    app.kubernetes.io/component: indexer
spec:
  selector:
    matchLabels:
      environment: {{ .Values.environment }}
      app.kubernetes.io/component: indexer
  replicas: 1 
  serviceName: {{ .Values.environment }}-indexer
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/indexer-configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        environment: {{ .Values.environment }}
        app.kubernetes.io/component: indexer
        {{- with .Values.podCommonLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: indexer
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["npm", "run", "start", "indexer"]
        envFrom:
        - configMapRef:
            name: {{.Release.Name }}-indexer-env